// 300+ words across 16 categories — Tagalog & English
// hints: easy = broad context | medium = indirect | hard = abstract/cryptic
const WORD_DATASET = [
  // ── Foods ──
  { word:"Adobo",       category:"Foods", hints:{easy:"Kitchen",    medium:"Sour",        hard:"Vinegar"}},
  { word:"Sinigang",    category:"Foods", hints:{easy:"Bowl",       medium:"Tamarind",    hard:"Sour"}},
  { word:"Lechon",      category:"Foods", hints:{easy:"Celebration",medium:"Crispy",      hard:"Fire"}},
  { word:"Kare-Kare",   category:"Foods", hints:{easy:"Stew",       medium:"Peanut",      hard:"Brown"}},
  { word:"Sisig",       category:"Foods", hints:{easy:"Sizzling",   medium:"Plate",       hard:"Smoke"}},
  { word:"Pizza",       category:"Foods", hints:{easy:"Delivery",   medium:"Slice",       hard:"Oven"}},
  { word:"Sushi",       category:"Foods", hints:{easy:"Japan",      medium:"Roll",        hard:"Chopsticks"}},
  { word:"Burger",      category:"Foods", hints:{easy:"Bun",        medium:"Stack",       hard:"Sesame"}},
  { word:"Ramen",       category:"Foods", hints:{easy:"Noodles",    medium:"Broth",       hard:"Steam"}},
  { word:"Tacos",       category:"Foods", hints:{easy:"Mexico",     medium:"Fold",        hard:"Shell"}},
  { word:"Pancit",      category:"Foods", hints:{easy:"Noodles",    medium:"Birthday",    hard:"Long"}},
  { word:"Lumpia",      category:"Foods", hints:{easy:"Roll",       medium:"Wrapper",     hard:"Crunch"}},
  { word:"Halo-Halo",   category:"Foods", hints:{easy:"Cold",       medium:"Shaved",      hard:"Ice"}},
  { word:"Tocino",      category:"Foods", hints:{easy:"Sweet",      medium:"Pink",        hard:"Cure"}},
  { word:"Balut",       category:"Foods", hints:{easy:"Egg",        medium:"Duck",        hard:"Shell"}},
  { word:"Pasta",       category:"Foods", hints:{easy:"Italy",      medium:"Sauce",       hard:"Boil"}},
  { word:"Fried Chicken",category:"Foods",hints:{easy:"Crispy",     medium:"Golden",      hard:"Grease"}},
  { word:"Bibimbap",    category:"Foods", hints:{easy:"Korea",      medium:"Mix",         hard:"Stone"}},
  { word:"Hotdog",      category:"Foods", hints:{easy:"Bun",        medium:"Grill",       hard:"Snap"}},
  { word:"Pad Thai",    category:"Foods", hints:{easy:"Thailand",   medium:"Wok",         hard:"Tangy"}},
  { word:"Tapsilog",    category:"Foods", hints:{easy:"Breakfast",  medium:"Tapa",        hard:"Silog"}},
  { word:"Champorado",  category:"Foods", hints:{easy:"Chocolate",  medium:"Porridge",    hard:"Morning"}},
  { word:"Dinuguan",    category:"Foods", hints:{easy:"Dark",       medium:"Pork",        hard:"Blood"}},
  { word:"Bibingka",    category:"Foods", hints:{easy:"Christmas",  medium:"Clay pot",    hard:"Charcoal"}},
  { word:"Puto",        category:"Foods", hints:{easy:"Steamed",    medium:"White",       hard:"Fluffy"}},
  // ── Animals ──
  { word:"Elephant",     category:"Animals",hints:{easy:"Africa",    medium:"Trunk",       hard:"Memory"}},
  { word:"Dolphin",      category:"Animals",hints:{easy:"Ocean",     medium:"Jump",        hard:"Echo"}},
  { word:"Penguin",      category:"Animals",hints:{easy:"Cold",      medium:"Waddle",      hard:"Tuxedo"}},
  { word:"Giraffe",      category:"Animals",hints:{easy:"Tall",      medium:"Savanna",     hard:"Reach"}},
  { word:"Tiger",        category:"Animals",hints:{easy:"Jungle",    medium:"Stripes",     hard:"Stalk"}},
  { word:"Panda",        category:"Animals",hints:{easy:"China",     medium:"Bamboo",      hard:"Rare"}},
  { word:"Tamaraw",      category:"Animals",hints:{easy:"Philippine",medium:"Mindoro",     hard:"Rare"}},
  { word:"Philippine Eagle",category:"Animals",hints:{easy:"Eagle",  medium:"Forest",      hard:"Soar"}},
  { word:"Tarsier",      category:"Animals",hints:{easy:"Small",     medium:"Eyes",        hard:"Night"}},
  { word:"Koala",        category:"Animals",hints:{easy:"Australia", medium:"Eucalyptus",  hard:"Drowsy"}},
  { word:"Sloth",        category:"Animals",hints:{easy:"Slow",      medium:"Hanging",     hard:"Still"}},
  { word:"Flamingo",     category:"Animals",hints:{easy:"Pink",      medium:"One leg",     hard:"Balance"}},
  { word:"Chameleon",    category:"Animals",hints:{easy:"Lizard",    medium:"Blend",       hard:"Shift"}},
  { word:"Octopus",      category:"Animals",hints:{easy:"Ocean",     medium:"Ink",         hard:"Arms"}},
  { word:"Axolotl",      category:"Animals",hints:{easy:"Salamander",medium:"Regrow",      hard:"Gills"}},
  { word:"Whale",        category:"Animals",hints:{easy:"Sea",       medium:"Massive",     hard:"Song"}},
  { word:"Cheetah",      category:"Animals",hints:{easy:"Africa",    medium:"Speed",       hard:"Blur"}},
  { word:"Peacock",      category:"Animals",hints:{easy:"Bird",      medium:"Feathers",    hard:"Display"}},
  { word:"Crocodile",    category:"Animals",hints:{easy:"River",     medium:"Teeth",       hard:"Still"}},
  { word:"Butterfly",    category:"Animals",hints:{easy:"Garden",    medium:"Wings",       hard:"Change"}},
  // ── Fruits ──
  { word:"Mango",        category:"Fruits",hints:{easy:"Tropical",  medium:"Yellow",      hard:"Sun"}},
  { word:"Durian",       category:"Fruits",hints:{easy:"Smell",     medium:"Spiky",       hard:"Banned"}},
  { word:"Strawberry",   category:"Fruits",hints:{easy:"Red",       medium:"Field",       hard:"Seed"}},
  { word:"Watermelon",   category:"Fruits",hints:{easy:"Summer",    medium:"Green",       hard:"Seed"}},
  { word:"Lanzones",     category:"Fruits",hints:{easy:"Cluster",   medium:"Sweet",       hard:"Peel"}},
  { word:"Rambutan",     category:"Fruits",hints:{easy:"Hairy",     medium:"Red",         hard:"Lychee"}},
  { word:"Banana",       category:"Fruits",hints:{easy:"Yellow",    medium:"Peel",        hard:"Curve"}},
  { word:"Avocado",      category:"Fruits",hints:{easy:"Green",     medium:"Toast",       hard:"Pit"}},
  { word:"Pineapple",    category:"Fruits",hints:{easy:"Tropical",  medium:"Crown",       hard:"Rings"}},
  { word:"Dragonfruit",  category:"Fruits",hints:{easy:"Pink",      medium:"Speckled",    hard:"Bloom"}},
  { word:"Jackfruit",    category:"Fruits",hints:{easy:"Giant",     medium:"Sticky",      hard:"Pulled"}},
  { word:"Coconut",      category:"Fruits",hints:{easy:"Beach",     medium:"Shell",       hard:"Thirst"}},
  { word:"Pomelo",       category:"Fruits",hints:{easy:"Citrus",    medium:"Pale",        hard:"Pith"}},
  { word:"Guava",        category:"Fruits",hints:{easy:"Tropical",  medium:"Seeds",       hard:"Pastel"}},
  { word:"Kiwi",         category:"Fruits",hints:{easy:"Fuzzy",     medium:"Green",       hard:"Tart"}},
  { word:"Papaya",       category:"Fruits",hints:{easy:"Orange",    medium:"Enzyme",      hard:"Soft"}},
  { word:"Santol",       category:"Fruits",hints:{easy:"Filipino",  medium:"Sour",        hard:"Pulp"}},
  { word:"Passion Fruit",category:"Fruits",hints:{easy:"Tropical",  medium:"Seeds",       hard:"Wrinkle"}},
  { word:"Calamansi",    category:"Fruits",hints:{easy:"Sour",      medium:"Tiny",        hard:"Squeeze"}},
  { word:"Chico",        category:"Fruits",hints:{easy:"Brown",     medium:"Sweet",       hard:"Gritty"}},
  // ── Sports ──
  { word:"Basketball",   category:"Sports",hints:{easy:"Hoop",      medium:"Bounce",      hard:"Net"}},
  { word:"Volleyball",   category:"Sports",hints:{easy:"Net",       medium:"Spike",       hard:"Rally"}},
  { word:"Swimming",     category:"Sports",hints:{easy:"Pool",      medium:"Float",       hard:"Breath"}},
  { word:"Boxing",       category:"Sports",hints:{easy:"Ring",      medium:"Glove",       hard:"Jab"}},
  { word:"Badminton",    category:"Sports",hints:{easy:"Racket",    medium:"Shuttle",     hard:"Feather"}},
  { word:"Football",     category:"Sports",hints:{easy:"Goal",      medium:"Kick",        hard:"Offside"}},
  { word:"Tennis",       category:"Sports",hints:{easy:"Court",     medium:"Serve",       hard:"Love"}},
  { word:"Gymnastics",   category:"Sports",hints:{easy:"Flip",      medium:"Vault",       hard:"Stick"}},
  { word:"Arnis",        category:"Sports",hints:{easy:"Stick",     medium:"Strike",      hard:"Rattan"}},
  { word:"Sepak Takraw", category:"Sports",hints:{easy:"Kick",      medium:"Rattan",      hard:"Aerial"}},
  { word:"Cycling",      category:"Sports",hints:{easy:"Pedal",     medium:"Wheel",       hard:"Draft"}},
  { word:"Archery",      category:"Sports",hints:{easy:"Arrow",     medium:"Target",      hard:"Release"}},
  { word:"Skateboarding",category:"Sports",hints:{easy:"Board",     medium:"Grind",       hard:"Concrete"}},
  { word:"Wrestling",    category:"Sports",hints:{easy:"Mat",       medium:"Grip",        hard:"Pin"}},
  { word:"Table Tennis", category:"Sports",hints:{easy:"Paddle",    medium:"Spin",        hard:"Ping"}},
  { word:"Golf",         category:"Sports",hints:{easy:"Club",      medium:"Fairway",     hard:"Birdie"}},
  { word:"Surfing",      category:"Sports",hints:{easy:"Wave",      medium:"Balance",     hard:"Tube"}},
  { word:"Baseball",     category:"Sports",hints:{easy:"Bat",       medium:"Diamond",     hard:"Strike"}},
  { word:"Marathon",     category:"Sports",hints:{easy:"Run",       medium:"Miles",       hard:"Wall"}},
  { word:"Fencing",      category:"Sports",hints:{easy:"Sword",     medium:"Lunge",       hard:"Touch"}},
  // ── Technology ──
  { word:"Laptop",       category:"Technology",hints:{easy:"Desk",    medium:"Screen",    hard:"Battery"}},
  { word:"Smartphone",   category:"Technology",hints:{easy:"Pocket",  medium:"Tap",       hard:"Swipe"}},
  { word:"Earbuds",      category:"Technology",hints:{easy:"Music",   medium:"Wireless",  hard:"Canal"}},
  { word:"Drone",        category:"Technology",hints:{easy:"Sky",     medium:"Camera",    hard:"Hover"}},
  { word:"Robot",        category:"Technology",hints:{easy:"Machine", medium:"Arm",       hard:"Servo"}},
  { word:"Satellite",    category:"Technology",hints:{easy:"Orbit",   medium:"Signal",    hard:"Ping"}},
  { word:"VR Headset",   category:"Technology",hints:{easy:"Virtual", medium:"Immersive", hard:"Latency"}},
  { word:"3D Printer",   category:"Technology",hints:{easy:"Layer",   medium:"Filament",  hard:"Extrude"}},
  { word:"Wi-Fi Router", category:"Technology",hints:{easy:"Signal",  medium:"Password",  hard:"SSID"}},
  { word:"Electric Car", category:"Technology",hints:{easy:"Battery", medium:"Charge",    hard:"Torque"}},
  { word:"Smart Watch",  category:"Technology",hints:{easy:"Wrist",   medium:"Fitness",   hard:"BPM"}},
  { word:"Keyboard",     category:"Technology",hints:{easy:"Type",    medium:"Keys",      hard:"Tactile"}},
  { word:"Camera",       category:"Technology",hints:{easy:"Photo",   medium:"Lens",      hard:"Aperture"}},
  { word:"Projector",    category:"Technology",hints:{easy:"Screen",  medium:"Beam",      hard:"Lumen"}},
  { word:"USB",          category:"Technology",hints:{easy:"Plug",    medium:"Transfer",  hard:"Bus"}},
  // ── Countries ──
  { word:"Philippines",  category:"Countries",hints:{easy:"Islands",     medium:"Archipelago",hard:"Luzon"}},
  { word:"Japan",        category:"Countries",hints:{easy:"Sushi",       medium:"Cherry blossom",hard:"Wa"}},
  { word:"South Korea",  category:"Countries",hints:{easy:"K-pop",       medium:"Kimchi",    hard:"Han"}},
  { word:"Brazil",       category:"Countries",hints:{easy:"Carnival",    medium:"Amazon",    hard:"Samba"}},
  { word:"Italy",        category:"Countries",hints:{easy:"Pasta",       medium:"Colosseum", hard:"Papal"}},
  { word:"Canada",       category:"Countries",hints:{easy:"Maple",       medium:"Hockey",    hard:"Tundra"}},
  { word:"Egypt",        category:"Countries",hints:{easy:"Pyramid",     medium:"Desert",    hard:"Pharaoh"}},
  { word:"India",        category:"Countries",hints:{easy:"Curry",       medium:"Ganges",    hard:"Vedic"}},
  { word:"Australia",    category:"Countries",hints:{easy:"Kangaroo",    medium:"Reef",      hard:"Outback"}},
  { word:"Mexico",       category:"Countries",hints:{easy:"Tacos",       medium:"Aztec",     hard:"Mariachi"}},
  { word:"France",       category:"Countries",hints:{easy:"Eiffel",      medium:"Baguette",  hard:"Liberté"}},
  { word:"Spain",        category:"Countries",hints:{easy:"Flamenco",    medium:"Tapas",     hard:"Ole"}},
  { word:"China",        category:"Countries",hints:{easy:"Dragon",      medium:"Dynasty",   hard:"Hanzi"}},
  { word:"USA",          category:"Countries",hints:{easy:"Hollywood",   medium:"Eagle",     hard:"Amendment"}},
  { word:"Nigeria",      category:"Countries",hints:{easy:"Africa",      medium:"Naira",     hard:"Lagos"}},
  // ── Filipino Culture ──
  { word:"Jeepney",      category:"Filipino Culture",hints:{easy:"Transport",  medium:"Colorful",  hard:"Pasada"}},
  { word:"Fiesta",       category:"Filipino Culture",hints:{easy:"Party",      medium:"Patron",    hard:"Procession"}},
  { word:"Bayanihan",    category:"Filipino Culture",hints:{easy:"Community",  medium:"Help",      hard:"Damayan"}},
  { word:"Terno",        category:"Filipino Culture",hints:{easy:"Dress",      medium:"Butterfly", hard:"Filipiniana"}},
  { word:"Parol",        category:"Filipino Culture",hints:{easy:"Christmas",  medium:"Star",      hard:"Lantern"}},
  { word:"Sorbetes",     category:"Filipino Culture",hints:{easy:"Ice cream",  medium:"Cart",      hard:"Dirty"}},
  { word:"Tabo",         category:"Filipino Culture",hints:{easy:"Bathroom",   medium:"Scoop",     hard:"Plastic"}},
  { word:"Palayok",      category:"Filipino Culture",hints:{easy:"Clay",       medium:"Pot",       hard:"Cook"}},
  { word:"Barong Tagalog",category:"Filipino Culture",hints:{easy:"Formal",    medium:"Pineapple", hard:"Piña"}},
  { word:"Sinulog",      category:"Filipino Culture",hints:{easy:"Festival",   medium:"Cebu",      hard:"Ati-Atihan"}},
  // ── Celebrities ──
  { word:"Manny Pacquiao",   category:"Celebrities",hints:{easy:"Boxing",     medium:"Senator",   hard:"Pound"}},
  { word:"Taylor Swift",     category:"Celebrities",hints:{easy:"Albums",     medium:"Era",       hard:"Easter egg"}},
  { word:"BTS",              category:"Celebrities",hints:{easy:"K-pop",      medium:"ARMY",      hard:"Bangtan"}},
  { word:"Vice Ganda",       category:"Celebrities",hints:{easy:"Comedy",     medium:"Noontime",  hard:"Beks"}},
  { word:"Lea Salonga",      category:"Celebrities",hints:{easy:"Musical",    medium:"Broadway",  hard:"Pitch"}},
  { word:"Lady Gaga",        category:"Celebrities",hints:{easy:"Pop",        medium:"Costume",   hard:"Monster"}},
  { word:"Lebron James",     category:"Celebrities",hints:{easy:"NBA",        medium:"Ring",      hard:"Chalk"}},
  { word:"Blackpink",        category:"Celebrities",hints:{easy:"K-pop",      medium:"YG",        hard:"Blink"}},
  { word:"Cristiano Ronaldo",category:"Celebrities",hints:{easy:"Football",   medium:"Siuuu",     hard:"CR7"}},
  { word:"Oprah Winfrey",    category:"Celebrities",hints:{easy:"Talk show",  medium:"Book club", hard:"You get"}},
  { word:"Anne Curtis",      category:"Celebrities",hints:{easy:"Actress",    medium:"Showtime",  hard:"Birit"}},
  { word:"Dwayne Johnson",   category:"Celebrities",hints:{easy:"Actor",      medium:"Gym",       hard:"Eyebrow"}},
  { word:"Elon Musk",        category:"Celebrities",hints:{easy:"Tech",       medium:"Rocket",    hard:"Tweet"}},
  { word:"Celine Dion",      category:"Celebrities",hints:{easy:"Ballad",     medium:"Titanic",   hard:"Range"}},
  { word:"Coco Martin",      category:"Celebrities",hints:{easy:"Probinsyano",medium:"Action",    hard:"Cardo"}},
  // ── Nature ──
  { word:"Rainbow",          category:"Nature",hints:{easy:"Colors",    medium:"Rain",        hard:"Refract"}},
  { word:"Volcano",          category:"Nature",hints:{easy:"Lava",      medium:"Erupt",       hard:"Magma"}},
  { word:"Aurora Borealis",  category:"Nature",hints:{easy:"Northern",  medium:"Solar",       hard:"Curtain"}},
  { word:"Tsunami",          category:"Nature",hints:{easy:"Wave",      medium:"Earthquake",  hard:"Surge"}},
  { word:"Coral Reef",       category:"Nature",hints:{easy:"Ocean",     medium:"Coral",       hard:"Bleach"}},
  { word:"Thunderstorm",     category:"Nature",hints:{easy:"Thunder",   medium:"Flash",       hard:"Charge"}},
  { word:"Mangrove",         category:"Nature",hints:{easy:"Roots",     medium:"Shore",       hard:"Tidal"}},
  { word:"Milky Way",        category:"Nature",hints:{easy:"Galaxy",    medium:"Stars",       hard:"Arm"}},
  { word:"Earthquake",       category:"Nature",hints:{easy:"Shake",     medium:"Fault",       hard:"P-wave"}},
  { word:"Waterfall",        category:"Nature",hints:{easy:"Falls",     medium:"Mist",        hard:"Plunge"}},
  { word:"Monsoon",          category:"Nature",hints:{easy:"Rain",      medium:"Season",      hard:"Circulation"}},
  { word:"Glacier",          category:"Nature",hints:{easy:"Ice",       medium:"Slow",        hard:"Moraine"}},
  { word:"Typhoon",          category:"Nature",hints:{easy:"Storm",     medium:"Signal",      hard:"Eye"}},
  { word:"Firefly",          category:"Nature",hints:{easy:"Glow",      medium:"Night",       hard:"Luciferin"}},
  { word:"Desert",           category:"Nature",hints:{easy:"Sand",      medium:"Dry",         hard:"Arid"}},
  // ── Professions ──
  { word:"Doctor",           category:"Professions",hints:{easy:"Hospital",  medium:"Stethoscope",hard:"Rounds"}},
  { word:"Teacher",          category:"Professions",hints:{easy:"School",    medium:"Chalk",      hard:"Syllabus"}},
  { word:"Chef",             category:"Professions",hints:{easy:"Kitchen",   medium:"Knife",      hard:"Mise"}},
  { word:"Engineer",         category:"Professions",hints:{easy:"Build",     medium:"Blueprint",  hard:"Torque"}},
  { word:"Pilot",            category:"Professions",hints:{easy:"Plane",     medium:"Cockpit",    hard:"Altimeter"}},
  { word:"Lawyer",           category:"Professions",hints:{easy:"Court",     medium:"Brief",      hard:"Tort"}},
  { word:"Nurse",            category:"Professions",hints:{easy:"Hospital",  medium:"Syringe",    hard:"Triage"}},
  { word:"Architect",        category:"Professions",hints:{easy:"Design",    medium:"Blueprint",  hard:"Cantilever"}},
  { word:"Astronaut",        category:"Professions",hints:{easy:"Space",     medium:"Orbit",      hard:"EVA"}},
  { word:"Firefighter",      category:"Professions",hints:{easy:"Fire",      medium:"Hose",       hard:"Flashover"}},
  { word:"Photographer",     category:"Professions",hints:{easy:"Camera",    medium:"Shutter",    hard:"Bokeh"}},
  { word:"Carpenter",        category:"Professions",hints:{easy:"Wood",      medium:"Nail",       hard:"Dovetail"}},
  { word:"Scientist",        category:"Professions",hints:{easy:"Lab",       medium:"Theory",     hard:"Hypothesis"}},
  { word:"Artist",           category:"Professions",hints:{easy:"Paint",     medium:"Canvas",     hard:"Palette"}},
  { word:"Farmer",           category:"Professions",hints:{easy:"Field",     medium:"Harvest",    hard:"Furrow"}},
  // ── Household Objects ──
  { word:"Refrigerator",     category:"Household Objects",hints:{easy:"Cold",    medium:"Hum",       hard:"Freon"}},
  { word:"Washing Machine",  category:"Household Objects",hints:{easy:"Clothes", medium:"Spin",      hard:"RPM"}},
  { word:"Sofa",             category:"Household Objects",hints:{easy:"Sit",     medium:"Cushion",   hard:"Ottoman"}},
  { word:"Mirror",           category:"Household Objects",hints:{easy:"Reflect", medium:"Vanity",    hard:"Silvering"}},
  { word:"Clock",            category:"Household Objects",hints:{easy:"Time",    medium:"Tick",      hard:"Escapement"}},
  { word:"Lamp",             category:"Household Objects",hints:{easy:"Light",   medium:"Shade",     hard:"Filament"}},
  { word:"Pillow",           category:"Household Objects",hints:{easy:"Sleep",   medium:"Soft",      hard:"Kapok"}},
  { word:"Broom",            category:"Household Objects",hints:{easy:"Sweep",   medium:"Bristle",   hard:"Straw"}},
  { word:"Kettle",           category:"Household Objects",hints:{easy:"Boil",    medium:"Steam",     hard:"Whistle"}},
  { word:"Curtain",          category:"Household Objects",hints:{easy:"Window",  medium:"Block",     hard:"Valance"}},
  { word:"Blender",          category:"Household Objects",hints:{easy:"Mix",     medium:"Blade",     hard:"RPM"}},
  { word:"Toaster",          category:"Household Objects",hints:{easy:"Bread",   medium:"Heat",      hard:"Browning"}},
  { word:"Scissors",         category:"Household Objects",hints:{easy:"Cut",     medium:"Blade",     hard:"Pivot"}},
  { word:"Padlock",          category:"Household Objects",hints:{easy:"Lock",    medium:"Key",       hard:"Tumbler"}},
  { word:"Umbrella",         category:"Household Objects",hints:{easy:"Rain",    medium:"Canopy",    hard:"Ribs"}},
  // ── Movies & Characters ──
  { word:"Titanic",          category:"Movies & Characters",hints:{easy:"Ship",     medium:"Iceberg",   hard:"Steerage"}},
  { word:"Avengers",         category:"Movies & Characters",hints:{easy:"Marvel",   medium:"Infinity",  hard:"Snap"}},
  { word:"Darna",            category:"Movies & Characters",hints:{easy:"Philippine",medium:"Stone",    hard:"Ding"}},
  { word:"Harry Potter",     category:"Movies & Characters",hints:{easy:"Wizard",   medium:"Wand",      hard:"Horcrux"}},
  { word:"Encanto",          category:"Movies & Characters",hints:{easy:"Family",   medium:"Gift",      hard:"Casita"}},
  { word:"Parasite",         category:"Movies & Characters",hints:{easy:"Korea",    medium:"Rich",      hard:"Basement"}},
  { word:"Batman",           category:"Movies & Characters",hints:{easy:"Gotham",   medium:"Cave",      hard:"Batarang"}},
  { word:"Mulan",            category:"Movies & Characters",hints:{easy:"China",    medium:"Honor",     hard:"Matchmaker"}},
  { word:"Spirited Away",    category:"Movies & Characters",hints:{easy:"Anime",    medium:"Bath house",hard:"Chihiro"}},
  { word:"Lion King",        category:"Movies & Characters",hints:{easy:"Africa",   medium:"Pride",     hard:"Hakuna"}},
  // ── Places ──
  { word:"Chocolate Hills",  category:"Places",hints:{easy:"Bohol",       medium:"Hills",        hard:"Conical"}},
  { word:"Intramuros",       category:"Places",hints:{easy:"Manila",      medium:"Walls",        hard:"Colonial"}},
  { word:"Mayon Volcano",    category:"Places",hints:{easy:"Bicol",       medium:"Perfect",      hard:"Cone"}},
  { word:"Boracay",          category:"Places",hints:{easy:"Beach",       medium:"White sand",   hard:"Station"}},
  { word:"Palawan",          category:"Places",hints:{easy:"Island",      medium:"Underground",  hard:"Pristine"}},
  { word:"Banaue Rice Terraces",category:"Places",hints:{easy:"Ifugao",   medium:"Terraces",     hard:"Eighth wonder"}},
  { word:"Eiffel Tower",     category:"Places",hints:{easy:"Paris",       medium:"Iron",         hard:"Gustave"}},
  { word:"Great Wall",       category:"Places",hints:{easy:"China",       medium:"Military",     hard:"Rammed"}},
  { word:"Colosseum",        category:"Places",hints:{easy:"Rome",        medium:"Gladiator",    hard:"Vomitorium"}},
  // ── School Items ──
  { word:"Pencil",           category:"School Items",hints:{easy:"Write",    medium:"Graphite",    hard:"HB"}},
  { word:"Ruler",            category:"School Items",hints:{easy:"Measure",  medium:"Straight",    hard:"Millimeter"}},
  { word:"Eraser",           category:"School Items",hints:{easy:"Mistake",  medium:"Rub",         hard:"Vinyl"}},
  { word:"Backpack",         category:"School Items",hints:{easy:"Carry",    medium:"Strap",       hard:"Lumbar"}},
  { word:"Globe",            category:"School Items",hints:{easy:"World",    medium:"Sphere",      hard:"Meridian"}},
  { word:"Calculator",       category:"School Items",hints:{easy:"Math",     medium:"Numbers",     hard:"Operand"}},
  { word:"Dictionary",       category:"School Items",hints:{easy:"Words",    medium:"Definition",  hard:"Lexicon"}},
  { word:"Microscope",       category:"School Items",hints:{easy:"Small",    medium:"Lens",        hard:"Ocular"}},
  { word:"Notebook",         category:"School Items",hints:{easy:"Write",    medium:"Spiral",      hard:"Ruled"}},
  // ── Vegetables ──
  { word:"Potatoes",         category:"Vegetables",hints:{easy:"Starchy",   medium:"Underground", hard:"Tuber"}},
  { word:"Okra",             category:"Vegetables",hints:{easy:"Sticky",    medium:"Pods",        hard:"Mucilage"}},
  { word:"Kangkong",         category:"Vegetables",hints:{easy:"Water spinach",medium:"Float",    hard:"Hollow"}},
  { word:"Ampalaya",         category:"Vegetables",hints:{easy:"Bitter",    medium:"Gourd",       hard:"Charantin"}},
  { word:"Corn",             category:"Vegetables",hints:{easy:"Yellow",    medium:"Cob",         hard:"Tassel"}},
  { word:"Carrot",           category:"Vegetables",hints:{easy:"Orange",    medium:"Rabbit",      hard:"Beta"}},
  { word:"Eggplant",         category:"Vegetables",hints:{easy:"Purple",    medium:"Grill",       hard:"Aubergine"}},
  { word:"Spinach",          category:"Vegetables",hints:{easy:"Green",     medium:"Popeye",      hard:"Oxalate"}},
  { word:"Cabbage",          category:"Vegetables",hints:{easy:"Leaves",    medium:"Wrap",        hard:"Crucifer"}},
  { word:"Onion",            category:"Vegetables",hints:{easy:"Cry",       medium:"Layer",       hard:"Allicin"}},
];

const CATEGORIES = [
  "Foods","Animals","Fruits","Vegetables","Sports","Professions",
  "Technology","Countries","Places","Household Objects","School Items",
  "Movies & Characters","Celebrities","Filipino Culture","Nature","Random Mix",
];

function getWordsByCategory(cat) {
  if (cat === "Random Mix") return WORD_DATASET;
  return WORD_DATASET.filter(w => w.category === cat);
}

function randomFrom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

module.exports = { WORD_DATASET, CATEGORIES, getWordsByCategory, randomFrom };
